---
- name: Update Apt Cache
  apt:
    update_cache: yes

- name: Import ScyllaDB GPG Key
  become: true
  raw: gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/keyrings/scylladb.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys d0a112e067426ab2

- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"

- name: Update Apt Cache
  apt:
    update_cache: yes

- name: Install Scylla
  apt:
    name: scylla
    state: present
  failed_when: false

- name: Run Scylla
  command: scylla_setup
  args:
    stdin: "YES\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nyes\nYES\nYES\nYES\nYES\nYES\nYES\nYES\nyes"
  register: scylla_setup_output
  changed_when: false
